kind: pipeline
name: academy-fe-drone
trigger:
  branch:
    - deploy

environment:
  DOCKER_IMAGE_NAME: academy-fe
  DOCKER_CONTAINER_NAME: academy-fe

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npm run build

  - name: build-docker-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t $DOCKER_IMAGE_NAME .

  - name: deploy-docker
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop $DOCKER_CONTAINER_NAME || true
      - docker rm $DOCKER_CONTAINER_NAME || true
      - docker run -d --name $DOCKER_CONTAINER_NAME -p 5168:3000 $DOCKER_IMAGE_NAME

  # - name: test
  #   image: docker:dind
  #   volumes:
  #     - name: dockersock
  #       path: /var/run/docker.sock
  #   commands:
  #     - docker ps -a

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
